// @generated by protobuf-ts 2.11.1 with parameter server_none
// @generated from protobuf file "naniue.proto" (package "naniue", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { Wpp } from "./naniue";
import type { Message } from "./naniue";
import type { ServerStreamingCall } from "@protobuf-ts/runtime-rpc";
import type { Empty } from "./naniue";
import type { SendMessageReq } from "./naniue";
import type { Contact } from "./naniue";
import type { GetContactReq } from "./naniue";
import type { Contacts } from "./naniue";
import type { BaseReq } from "./naniue";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { LoginRes } from "./naniue";
import type { LoginReq } from "./naniue";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service naniue.Wpp
 */
export interface IWppClient {
    /**
     * @generated from protobuf rpc: Login
     */
    login(input: LoginReq, options?: RpcOptions): UnaryCall<LoginReq, LoginRes>;
    /**
     * @generated from protobuf rpc: GetContacts
     */
    getContacts(input: BaseReq, options?: RpcOptions): UnaryCall<BaseReq, Contacts>;
    /**
     * @generated from protobuf rpc: GetContact
     */
    getContact(input: GetContactReq, options?: RpcOptions): UnaryCall<GetContactReq, Contact>;
    /**
     * @generated from protobuf rpc: SendMessage
     */
    sendMessage(input: SendMessageReq, options?: RpcOptions): UnaryCall<SendMessageReq, Empty>;
    /**
     * @generated from protobuf rpc: SubscribeMessages
     */
    subscribeMessages(input: BaseReq, options?: RpcOptions): ServerStreamingCall<BaseReq, Message>;
}
/**
 * @generated from protobuf service naniue.Wpp
 */
export class WppClient implements IWppClient, ServiceInfo {
    typeName = Wpp.typeName;
    methods = Wpp.methods;
    options = Wpp.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: Login
     */
    login(input: LoginReq, options?: RpcOptions): UnaryCall<LoginReq, LoginRes> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<LoginReq, LoginRes>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetContacts
     */
    getContacts(input: BaseReq, options?: RpcOptions): UnaryCall<BaseReq, Contacts> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<BaseReq, Contacts>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetContact
     */
    getContact(input: GetContactReq, options?: RpcOptions): UnaryCall<GetContactReq, Contact> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetContactReq, Contact>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: SendMessage
     */
    sendMessage(input: SendMessageReq, options?: RpcOptions): UnaryCall<SendMessageReq, Empty> {
        const method = this.methods[3], opt = this._transport.mergeOptions(options);
        return stackIntercept<SendMessageReq, Empty>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: SubscribeMessages
     */
    subscribeMessages(input: BaseReq, options?: RpcOptions): ServerStreamingCall<BaseReq, Message> {
        const method = this.methods[4], opt = this._transport.mergeOptions(options);
        return stackIntercept<BaseReq, Message>("serverStreaming", this._transport, method, opt, input);
    }
}
